/**
 * A news rotator with prev/next implementation and ability to play/stop.
 * 
 * @version		1.0
 * 
 * @license		MIT-style license
 * @author		Djamil Legato <djamil [at] djamil.it>
 * @copyright	Author
 */

eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('9 X=8 1d({1e:\'1.3\',7:{s:1f,Y:1g,Z:N,10:C,D:C,11:C,E:\'1h-h/1i/1j/p/1k.1l\'},1m:6(a,b){5.F=$(a);5.1n(b);5.p=5.F.1o(\'.1p > G\');5.h=$$(\'#\'+a+\' .O-12 H.O\');5.m=0;5.13();5.14();5.y=\'n\';q(5.7.Z)1q.I(\'1r\',5.k.o(5));l 5},13:6(){9 b=5;$$(5.h,5.p).J(\'1s\',\'1t\');9 c=5.p.P(1);9 d=5.h.P(1);c.r(6(a){a.15(5.p[0]).J(\'z\',0)},5);d.r(6(a){a.15(5.h[0]).J(\'z\',0)},5);9 e=$$(\'.O-12\').P(1);e.r(6(a){a.1u().1v()});9 f=8 t(\'H\',{\'u\':\'D\'}).v(5.F);5.16=8 t(\'G\',{\'u\':\'A-17\',\'Q\':\'1w\',\'R\':\'17\',\'S\':5.7.E}).v(f);5.18=8 t(\'G\',{\'u\':\'A-B\',\'Q\':\'1x\',\'R\':\'B\',\'S\':5.7.E}).v(f);5.19=8 t(\'G\',{\'1y\':\'k-n\',\'u\':\'A-n\',\'Q\':\'1z/1A\',\'R\':\'k/n\',\'S\':5.7.E}).v(f);q(!5.7.D)f.J(\'1B\',\'1C\');q(5.7.11&&5.7.D){9 g=8 T.U(f,\'z\',{1D:N}).1E(0);5.F.1F({\'1G\':g.w.o(g,1),\'1H\':g.w.o(g,0)})};q(5.7.10){(5.p.K).L(6(i){(2).L(6(j){8 t(\'H\',{\'u\':\'i\'+(j+1)}).v(5.p[i])}.o(5))}.o(5))}(4).L(6(i){8 t(\'H\',{\'u\':\'1I c\'+(i+1)}).v(5.h[0].1J())}.o(5));5.x=[];(5.h.K).L(6(i){5.x[i]=[8 T.U(5.p[i],\'z\',{s:5.7.s,1K:6(){b.M=C},1L:6(){b.M=N}}),8 T.U(5.h[i],\'z\',{s:5.7.s})]}.o(5));l 5},14:6(){9 a=5,V=$(\'k-n\');5.16.I(\'W\',5.1a.o(5));5.18.I(\'W\',5.B.o(5));5.19.I(\'W\',6(){q(a.y==\'k\'){a.n();V.1b=\'A-k\'}1M{a.k();V.1b=\'A-n\'}});l 5},1a:6(){q(5.M)l 5;9 b=(!5.m)?5.h.K-1:5.m-1;5.x[5.m].r(6(a){a.w(0)});5.x[b].r(6(a){a.w(1)});5.m=b;l 5},B:6(){q(5.M)l 5;9 b=(5.m==5.h.K-1)?0:5.m+1;5.x[5.m].r(6(a){a.w(0)});5.x[b].r(6(a){a.w(1)});5.m=b;l 5},k:6(){q(5.y==\'k\')l 5;5.y=\'k\';5.1c=5.B.1N(5.7.Y+5.7.s,5);l 5},n:6(){5.y=\'n\';$1O(5.1c);l 5}});X.1P(8 1Q,8 1R);',62,116,'|||||this|function|options|new|var||||||||content|||play|return|current|stop|bind|images|if|each|duration|Element|class|inject|start|fx|status|opacity|control|next|true|controls|blankimage|container|img|div|addEvent|setStyle|length|times|transitioning|false|story|slice|title|alt|src|Fx|Style|playstop|click|NewsRotator|delay|autoplay|corners|autohide|block|build|attachEvents|injectAfter|arrowPrev|prev|arrowNext|arrowPlay|previous|className|timer|Class|version|1000|5000|wp|themes|Simplix|blank|png|initialize|setOptions|getElements|image|window|load|position|absolute|empty|remove|Previous|Next|id|Play|Stop|display|none|wait|set|addEvents|mouseenter|mouseleave|corner|getParent|onStart|onComplete|else|periodical|clear|implement|Events|Options'.split('|'),0,{}))