/* Copyright 2007 - 2011 YOOtheme GmbH, YOOtheme Proprietary Use License (http://www.yootheme.com/license) */

(function(c){var m=function(){};c.extend(m.prototype,{name:"dropdownMenu",options:{mode:"default",itemSelector:"li",firstLevelSelector:"li.level1",dropdownSelector:"ul",duration:600,remainTime:800,remainClass:"remain",transition:"easeOutExpo",withopacity:true,centerDropdown:false,reverseAnimation:false,fixWidth:false,fancy:null},initialize:function(i,d){this.options=c.extend({},this.options,d);var a=this,l=null,q=false;this.menu=i;this.dropdowns=[];this.options.withopacity=c.browser.msie&&parseFloat(c.browser.version)<
9?false:this.options.withopacity;if(this.options.fixWidth){var t=5;this.menu.children().each(function(){t+=c(this).width()});this.menu.css("width",t)}this.menu.find(this.options.firstLevelSelector).each(function(k){var g=c(this),h=g.find(a.options.dropdownSelector).css({overflow:"hidden"});if(h.length){h.css("overflow","hidden");var e=c("<div>").data("dpwidth",parseFloat(h.width())).data("dpheight",parseFloat(h.height())).css({overflow:"hidden"}).append("<div></div>"),u=e.find("div:first").css({"min-width":e.data("dpwidth"),
"min-height":e.data("dpheight")});h.children().appendTo(u);e.appendTo(h);a.options.centerDropdown&&h.css("margin-left",(parseFloat(h.css("width"))/2-g.width()/2)*-1);a.dropdowns.push({dropdown:h,div:e,innerdiv:u})}g.bind({mouseenter:function(){q=true;a.menu.trigger("menu:enter",[g,k]);if(l){if(l.index==k)return;l.item.removeClass(a.options.remainClass);l.div.hide()}if(h.length){g.addClass(a.options.remainClass);e.stop().show();var f=e.data("dpwidth"),j=e.data("dpheight");switch(a.options.mode){case "diagonal":var b=
{width:0,height:0};f={width:f,height:j};if(a.options.withopacity){b.opacity=0;f.opacity=1}e.css(b).animate(f,a.options.duration,a.options.transition);break;case "height":b={width:f,height:0};f={height:j};if(a.options.withopacity){b.opacity=0;f.opacity=1}e.css(b).animate(f,a.options.duration,a.options.transition);break;case "width":b={width:0,height:j};f={width:f};if(a.options.withopacity){b.opacity=0;f.opacity=1}e.css(b).animate(f,a.options.duration,a.options.transition);break;case "slide":h.css({width:f,
height:j});e.css({width:f,height:j,"margin-top":j*-1}).animate({"margin-top":0},a.options.duration,a.options.transition);break;default:b={width:f,height:j};f={};if(a.options.withopacity){b.opacity=0;f.opacity=1}e.css(b).animate(f,a.options.duration,a.options.transition)}l={item:g,div:e,index:k}}else l=active=null},mouseleave:function(f){if(f.srcElement&&c(f.srcElement).hasClass("module"))return false;q=false;h.length?window.setTimeout(function(){if(!(q||e.css("display")=="none")){a.menu.trigger("menu:leave",
[g,k]);var j=function(){g.removeClass(a.options.remainClass);l=null;e.hide()};if(a.options.reverseAnimation)switch(a.options.mode){case "diagonal":var b={width:0,height:0};if(a.options.withopacity)b.opacity=0;e.stop().animate(b,a.options.duration,a.options.transition,function(){j()});break;case "height":b={height:0};if(a.options.withopacity)b.opacity=0;e.stop().animate(b,a.options.duration,a.options.transition,function(){j()});break;case "width":b={width:0};if(a.options.withopacity)b.opacity=0;e.stop().animate(b,
a.options.duration,a.options.transition,function(){j()});break;case "slide":e.stop().animate({"margin-top":parseFloat(e.data("dpheight"))*-1},a.options.duration,a.options.transition,function(){j()});break;default:b={};if(a.options.withopacity)b.opacity=0;e.stop().animate(b,a.options.duration,a.options.transition,function(){j()})}else j()}},a.options.remainTime):a.menu.trigger("menu:leave")}})});if(this.options.fancy){var n=c.extend({mode:"move",transition:"easeOutExpo",duration:500,onEnter:null,onLeave:null},
this.options.fancy),o=this.menu.append('<div class="fancy bg1"><div class="fancy-1"><div class="fancy-2"><div class="fancy-3"></div></div></div></div>').find(".fancy:first").hide(),p=this.menu.find(".active:first"),r=null,s=function(k,g){if(!(g&&r&&k.get(0)==r.get(0))){o.stop().show().css("visibility","visible");if(n.mode=="move")!p.length&&!g?o.hide():o.animate({left:k.position().left+"px",width:k.width()+"px"},n.duration,n.transition);else g?o.css({opacity:p?0:1,left:k.position().left+"px",width:k.width()+
"px"}).animate({opacity:1},n.duration):o.animate({opacity:0},n.duration);r=g?k:null}};this.menu.bind({"menu:enter":function(k,g,h){s(g,true);if(n.onEnter)n.onEnter(g,h,o)},"menu:leave":function(k,g,h){s(p,false);if(n.onLeave)n.onLeave(g,h,o)}});p.length&&n.mode=="move"&&s(p,true)}},matchHeight:function(){if(this.menu){this.menu.find("li.level2 div.sub").each(function(){var i=c(this),d=i.parent().find("div.hover-box4:first"),a=Math.max(i.height(),d.height());c([i,d]).each(function(){this.css("height",
a)})});this._updateDimensions()}},matchUlHeight:function(){if(this.menu){this.menu.find("div.dropdown-3").each(function(){var i=c(this).children(),d=0;c(i).each(function(){d=Math.max(c(this).height(),d)});c(i).each(function(){c(this).css("height",d)})});this._updateDimensions()}},_updateDimensions:function(){c(this.dropdowns).each(function(i,d){d.div.stop().show().data({dpwidth:d.innerdiv.width(),dpheight:d.innerdiv.height()}).hide();d.dropdown.css({"min-width":d.div.data("dpwidth"),"min-height":d.div.data("dpheight")})})}});
c.fn[m.prototype.name]=function(){var i=arguments,d=i[0]?i[0]:null;return this.each(function(){var a=c(this);if(m.prototype[d]&&a.data(m.prototype.name)&&d!="initialize")a.data(m.prototype.name)[d].apply(a.data(m.prototype.name),Array.prototype.slice.call(i,1));else if(!d||c.isPlainObject(d)){var l=new m;m.prototype.initialize&&l.initialize.apply(l,c.merge([a],i));a.data(m.prototype.name,l)}else c.error("Method "+d+" does not exist on jQuery."+m.name)})}})(jQuery);
