/* Copyright (C) YOOtheme GmbH, YOOtheme Proprietary Use License (http://www.yootheme.com/license) */

(function(e){var f={};e.fn.socialButtons=function(a){a=e.extend({wrapper:'<div class="socialbuttons" />'},a);if(!a.twitter&&!a.plusone)return this;a.twitter&&!f.twitter&&(f.twitter=e.getScript("//platform.twitter.com/widgets.js"));a.plusone&&!f.plusone&&(f.plusone=e.getScript("//apis.google.com/js/plusone.js"));return this.each(function(){var b=e(this).data("permalink"),c=e(a.wrapper).appendTo(this);a.twitter&&c.append('<div><a href="http://twitter.com/share" class="twitter-share-button" data-url="'+
b+'" data-count="none">Tweet</a></div>');a.plusone&&c.append('<div><div class="g-plusone" data-size="medium" data-annotation="none" data-href="'+b+'"></div></div>')})};e.fn.matchHeight=function(a){var b=0,c=[];this.each(function(){var b=a?e(this).find(a+":first"):e(this);c.push(b);b.css("min-height","")});this.each(function(){b=Math.max(b,e(this).outerHeight())});return this.each(function(a){var g=e(this),a=c[a],g=a.height()+(b-g.outerHeight());a.css("min-height",g+"px")})};e.fn.matchWidth=function(a){return this.each(function(){var b=
e(this),c=b.children(a),d=0;c.width(function(a,f){return a<c.length-1?(d+=f,f):b.width()-d})})};e.fn.smoothScroller=function(a){a=e.extend({duration:1E3,transition:"easeOutExpo"},a);return this.each(function(){e(this).bind("click",function(){var b=this.hash,c=e(this.hash).offset().top,d=window.location.href.replace(window.location.hash,""),g=e.browser.opera?"html:not(:animated)":"html:not(:animated),body:not(:animated)";if(d+b==this)return e(g).animate({scrollTop:c},a.duration,a.transition,function(){window.location.hash=
b.replace("#","")}),!1})})}})(jQuery);
(function(e){e.easing.jswing=e.easing.swing;e.extend(e.easing,{def:"easeOutQuad",swing:function(f,a,b,c,d){return e.easing[e.easing.def](f,a,b,c,d)},easeInQuad:function(f,a,b,c,d){return c*(a/=d)*a+b},easeOutQuad:function(f,a,b,c,d){return-c*(a/=d)*(a-2)+b},easeInOutQuad:function(f,a,b,c,d){return(a/=d/2)<1?c/2*a*a+b:-c/2*(--a*(a-2)-1)+b},easeInCubic:function(f,a,b,c,d){return c*(a/=d)*a*a+b},easeOutCubic:function(f,a,b,c,d){return c*((a=a/d-1)*a*a+1)+b},easeInOutCubic:function(f,a,b,c,d){return(a/=
d/2)<1?c/2*a*a*a+b:c/2*((a-=2)*a*a+2)+b},easeInQuart:function(f,a,b,c,d){return c*(a/=d)*a*a*a+b},easeOutQuart:function(f,a,b,c,d){return-c*((a=a/d-1)*a*a*a-1)+b},easeInOutQuart:function(f,a,b,c,d){return(a/=d/2)<1?c/2*a*a*a*a+b:-c/2*((a-=2)*a*a*a-2)+b},easeInQuint:function(f,a,b,c,d){return c*(a/=d)*a*a*a*a+b},easeOutQuint:function(f,a,b,c,d){return c*((a=a/d-1)*a*a*a*a+1)+b},easeInOutQuint:function(f,a,b,c,d){return(a/=d/2)<1?c/2*a*a*a*a*a+b:c/2*((a-=2)*a*a*a*a+2)+b},easeInSine:function(f,a,b,c,
d){return-c*Math.cos(a/d*(Math.PI/2))+c+b},easeOutSine:function(f,a,b,c,d){return c*Math.sin(a/d*(Math.PI/2))+b},easeInOutSine:function(f,a,b,c,d){return-c/2*(Math.cos(Math.PI*a/d)-1)+b},easeInExpo:function(f,a,b,c,d){return a==0?b:c*Math.pow(2,10*(a/d-1))+b},easeOutExpo:function(f,a,b,c,d){return a==d?b+c:c*(-Math.pow(2,-10*a/d)+1)+b},easeInOutExpo:function(f,a,b,c,d){return a==0?b:a==d?b+c:(a/=d/2)<1?c/2*Math.pow(2,10*(a-1))+b:c/2*(-Math.pow(2,-10*--a)+2)+b},easeInCirc:function(f,a,b,c,d){return-c*
(Math.sqrt(1-(a/=d)*a)-1)+b},easeOutCirc:function(f,a,b,c,d){return c*Math.sqrt(1-(a=a/d-1)*a)+b},easeInOutCirc:function(f,a,b,c,d){return(a/=d/2)<1?-c/2*(Math.sqrt(1-a*a)-1)+b:c/2*(Math.sqrt(1-(a-=2)*a)+1)+b},easeInElastic:function(f,a,b,c,d){var f=1.70158,g=0,e=c;if(a==0)return b;if((a/=d)==1)return b+c;g||(g=d*0.3);e<Math.abs(c)?(e=c,f=g/4):f=g/(2*Math.PI)*Math.asin(c/e);return-(e*Math.pow(2,10*(a-=1))*Math.sin((a*d-f)*2*Math.PI/g))+b},easeOutElastic:function(f,a,b,c,d){var f=1.70158,g=0,e=c;if(a==
0)return b;if((a/=d)==1)return b+c;g||(g=d*0.3);e<Math.abs(c)?(e=c,f=g/4):f=g/(2*Math.PI)*Math.asin(c/e);return e*Math.pow(2,-10*a)*Math.sin((a*d-f)*2*Math.PI/g)+c+b},easeInOutElastic:function(f,a,b,c,d){var f=1.70158,g=0,e=c;if(a==0)return b;if((a/=d/2)==2)return b+c;g||(g=d*0.3*1.5);e<Math.abs(c)?(e=c,f=g/4):f=g/(2*Math.PI)*Math.asin(c/e);return a<1?-0.5*e*Math.pow(2,10*(a-=1))*Math.sin((a*d-f)*2*Math.PI/g)+b:e*Math.pow(2,-10*(a-=1))*Math.sin((a*d-f)*2*Math.PI/g)*0.5+c+b},easeInBack:function(e,
a,b,c,d,g){g==void 0&&(g=1.70158);return c*(a/=d)*a*((g+1)*a-g)+b},easeOutBack:function(e,a,b,c,d,g){g==void 0&&(g=1.70158);return c*((a=a/d-1)*a*((g+1)*a+g)+1)+b},easeInOutBack:function(e,a,b,c,d,g){g==void 0&&(g=1.70158);return(a/=d/2)<1?c/2*a*a*(((g*=1.525)+1)*a-g)+b:c/2*((a-=2)*a*(((g*=1.525)+1)*a+g)+2)+b},easeInBounce:function(f,a,b,c,d){return c-e.easing.easeOutBounce(f,d-a,0,c,d)+b},easeOutBounce:function(e,a,b,c,d){return(a/=d)<1/2.75?c*7.5625*a*a+b:a<2/2.75?c*(7.5625*(a-=1.5/2.75)*a+0.75)+
b:a<2.5/2.75?c*(7.5625*(a-=2.25/2.75)*a+0.9375)+b:c*(7.5625*(a-=2.625/2.75)*a+0.984375)+b},easeInOutBounce:function(f,a,b,c,d){return a<d/2?e.easing.easeInBounce(f,a*2,0,c,d)*0.5+b:e.easing.easeOutBounce(f,a*2-d,0,c,d)*0.5+c*0.5+b}})})(jQuery);
(function(e){function f(a){var c={},b=/^jQuery\d+$/;e.each(a.attributes,function(a,d){if(d.specified&&!b.test(d.name))c[d.name]=d.value});return c}function a(){var a=e(this);a.val()===a.attr("placeholder")&&a.hasClass("placeholder")&&(a.data("placeholder-password")?a.hide().next().show().focus():a.val("").removeClass("placeholder"))}function b(){var c,b=e(this);if(b.val()===""||b.val()===b.attr("placeholder")){if(b.is(":password")){if(!b.data("placeholder-textinput")){try{c=b.clone().attr({type:"text"})}catch(d){c=
e("<input>").attr(e.extend(f(b[0]),{type:"text"}))}c.removeAttr("name").data("placeholder-password",!0).bind("focus.placeholder",a);b.data("placeholder-textinput",c).before(c)}b=b.hide().prev().show()}b.addClass("placeholder").val(b.attr("placeholder"))}else b.removeClass("placeholder")}var c="placeholder"in document.createElement("input"),d="placeholder"in document.createElement("textarea");e.fn.placeholder=c&&d?function(){return this}:function(){return this.filter((c?"textarea":":input")+"[placeholder]").bind("focus.placeholder",
a).bind("blur.placeholder",b).trigger("blur.placeholder").end()};e(function(){e("form").bind("submit.placeholder",function(){var c=e(".placeholder",this).each(a);setTimeout(function(){c.each(b)},10)})});e(window).bind("unload.placeholder",function(){e(".placeholder").val("")})})(jQuery);
